### ISSUE TITLE
Set up an automated Docker build

### ISSUE THREAD

**Issue by f-lopes** [michelin/ChopChop#18]
Currently, there is no automated Docker build nor a published image on Docker Hub (hub.docker.com).

It could be great to set up an automated Docker build to build & push the last Docker image to the Docker Hub.

The usage with Docker would then be straightforward:
```bash
docker run michelin/chopchop scan --url https://foobar.com
```

This simple process is well explained here: https://docs.docker.com/docker-hub/builds/.
I can't set up this build myself as I am not owner of this repository.

You can see here a sample on the forked repository:
![image](https://user-images.githubusercontent.com/5397640/87574551-d2c65f80-c6ce-11ea-9333-51623223c7c4.png)

**Comment by PaulSec** [comment]
Hey Florian, good issue! We are checking this internally because you can't give access to specific repos to Dockerhub, it has to access them all and I don't think it would be necessary. 

We will let you know ASAP about this!

**Comment by PaulSec** [comment]
Hey everyone, 

We started using the Github Container Registry and thanks to @shayneburgess 

You can pull the latest build from: 

```bash
$ docker pull ghcr.io/michelin/gochopchop:latest
```

🔥🔥🔥🔥
