### ISSUE TITLE
Detect the non-presence of a HTTP header

### ISSUE THREAD

**Issue by S0obi** [michelin/ChopChop#7]
Hello everyone, thanks for sharing ChopChop.

According to the [documentation](https://github.com/michelin/ChopChop#creating-a-new-check), there is no way to detect the lack of a HTTP header.

It can be a nice feature to detect the absence of some security headers like "Strict-Transport-Security" or "Content-Security-Policy".

**Comment by PaulSec** [comment]
Hi there @S0obi, I created a pull request for this specify issue. 
Would you mind trying this solution and let me know if that suits you? 

Cheers!
